AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This stack is meant to be manually created in the AWS Console by referring to
  the uploaded template in the ArtifactBucket.  Creates the BuildChangeSet
  codebuild resource that is used to create a change set from uploaded artifacts
  in a S3 bucket.

Metadata:
  Author: Jake Hickenlooper

Parameters:

  ProjectSlug:
    Type: String
    Description: >
      A one word name of the project. Used as part of the object key name for
      uploaded cloudformation templates and parameter JSON files.

      Will be used for root object name in
      buckets and other places. The Parameter Store in AWS Systems Manager will
      use this as the prefix (like /weboftomorrow/) for parameters.
    Default: "weboftomorrow"
    AllowedPattern: "[a-z0-9]+"
    MinLength: 3
    MaxLength: 50

  GitHubCloneURL:
    Type: String
    Description: >
      The https clone URL for the project.
    Default: ""

  ManualVerificationEmail:
    Type: String
    Description: >
      Email address to send a notification to when the staging site needs to be
      manually verified.
    Default: ""


Resources:

  BuildChangeSet:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub "${ProjectSlug}-BuildChangeSet"
      Artifacts:
        Type: NO_ARTIFACTS
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Sub "${ProjectSlug}-BuildChangeSet"
          Status: ENABLED
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/standard:4.0"
        ImagePullCredentialsType: CODEBUILD
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          -
            Name: ARTIFACT_BUCKET
            Type: PLAINTEXT
            Value:
              Fn::ImportValue: "root-ArtifactBucket"
          -
            Name: STACK_NAME
            Type: PLAINTEXT
            Value: !Ref ProjectSlug
          -
            Name: REGION
            Type: PLAINTEXT
            Value: !Ref "AWS::Region"
      QueuedTimeoutInMinutes: 10
      ServiceRole:
        Fn::ImportValue: root-weboftomorrowBuildChangeSetRoleArn
      TimeoutInMinutes: 10
      Source:
        Location: !Sub
          - "${artifactBucket}/cloudformation/source-templates/${ProjectSlug}/"
          -
            artifactBucket:
              Fn::ImportValue: "root-ArtifactBucket"
        Type: S3
        BuildSpec: |
          version: 0.2
          env:
            shell: bash
            parameter-store:
              SECRET_HEADER_STRING: /weboftomorrow/secret-header-string
            variables:
              ARTIFACT_BUCKET: ""
              STACK_NAME: ""
              REGION: ""
          phases:
            build:
              commands:
                - BLUE_VERSION=$(jq -r '.[] | select(.ParameterKey == "BlueVersion") | .ParameterValue' parameters.json)
                - GREEN_VERSION=$(jq -r '.[] | select(.ParameterKey == "GreenVersion") | .ParameterValue' parameters.json)
                - CHANGE_SET_NAME=$(echo "version-bump-${BLUE_VERSION}-to-${GREEN_VERSION}" | tr --squeeze-repeats [:punct:] '-')
                - CHANGE_SET_TYPE=UPDATE
                - TMP_DIR=$(mktemp -d)
                - >
                    aws cloudformation describe-stacks \
                      --stack-name ${STACK_NAME}-pipeline || CHANGE_SET_TYPE=CREATE

                - 'echo "Change Set: ${CHANGE_SET_NAME}" for ${CHANGE_SET_TYPE}'

                # Secret string in the Referer header that CloudFront will use when accessing
                # files from the S3 bucket. This blocks direct public access of the static sites
                # bucket unless the Referer header with this string is used.
                - |
                    cat << HERE > $TMP_DIR/secret-header.json
                    [
                      {
                        "ParameterKey": "SecretHeaderString",
                        "ParameterValue": "$SECRET_HEADER_STRING"
                      }
                    ]
                    HERE
                    jq --raw-output --slurp \
                      '.[0] as $a1 | .[1] as $a2 | ($a1 + $a2)
                        | map(
                          select(
                            .ParameterKey == "ProjectSlug"
                            or .ParameterKey == "GitBranchToBuildFrom"
                            or .ParameterKey == "PatternToTriggerBuild"
                            or .ParameterKey == "SecretHeaderString"
                          )
                        )' \
                      parameters.json $TMP_DIR/secret-header.json > $TMP_DIR/parameters-pipeline.json
                - >
                    aws cloudformation package \
                      --template-file pipeline.yaml \
                      --s3-bucket $ARTIFACT_BUCKET \
                      --s3-prefix cloudformation/package-templates/${STACK_NAME} \
                      --output-template-file pipeline.yaml;

                - aws s3 cp pipeline.yaml s3://${ARTIFACT_BUCKET}/cloudformation/package-templates/${STACK_NAME}/

                - >
                    aws cloudformation create-change-set \
                      --change-set-name $CHANGE_SET_NAME \
                      --stack-name ${STACK_NAME}-pipeline \
                      --change-set-type $CHANGE_SET_TYPE \
                      --capabilities CAPABILITY_NAMED_IAM \
                      --parameters file://$TMP_DIR/parameters-pipeline.json \
                      --template-url "https://${ARTIFACT_BUCKET}.s3-${REGION}.amazonaws.com/cloudformation/package-templates/${STACK_NAME}/pipeline.yaml" \
                      --output text \
                      --query 'Id'

Outputs:
  GitHubCloneURL:
    Value: !Ref GitHubCloneURL
    Export:
      Name: !Sub "${ProjectSlug}-GitHubCloneURL"

  ManualVerificationEmail:
    Value: !Ref ManualVerificationEmail
    Export:
      Name: !Sub "${ProjectSlug}-ManualVerificationEmail"
