AWSTemplateFormatVersion: "2010-09-09"


Description: >
  A static site backed by CloudFront CDN. Uses a blue-green deployment via two
  origins in an origin group. The origins can be swapped when needing to revert
  a blue-green deployment.

Metadata:
  Author: Jake Hickenlooper

Parameters:
  ProjectSlug:
    Type: String
  BlueVersion:
    Type: String
  GreenVersion:
    Type: String

  SecretHeaderString:
    Type: String

  HostedZoneId:
    Type: 'AWS::Route53::HostedZone::Id'

Resources:

  CloudFrontProduction:
    Type: 'AWS::CloudFront::Distribution'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DistributionConfig:
        Comment: >
          The origins in the origin group can be swapped when reverting the
          blue-green deployment.
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: "blue-green-failover"
          # Managed-CachingOptimized
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        PriceClass: PriceClass_All
        OriginGroups:
          Items:
            -
              Id: "blue-green-failover"
              FailoverCriteria:
                StatusCodes:
                  Items:
                    - 404
                  Quantity: 1
              Members:
                Items:
                  -
                    OriginId: "green"
                  -
                    OriginId: "blue"
                Quantity: 2
          Quantity: 2
        Origins:
          -
            Id: "blue"
            CustomOriginConfig:
              # The S3 static website is only accessible via http
              OriginProtocolPolicy: http-only
            DomainName: !Select
              - 1
              - !Split
                - "://"
                - Fn::ImportValue: root-StaticWebsiteURL
            OriginCustomHeaders:
              -
                HeaderName: Referer
                HeaderValue: !Ref SecretHeaderString
            OriginPath: !Sub "/${ProjectSlug}/production/${BlueVersion}"
          -
            Id: "green"
            CustomOriginConfig:
              # The S3 static website is only accessible via http
              OriginProtocolPolicy: http-only
            #DomainName: !Select [1, !Split ["://", !GetAtt StaticSiteFiles.WebsiteURL]]
            DomainName: !Select
              - 1
              - !Split
                - "://"
                - Fn::ImportValue: root-StaticWebsiteURL
            OriginCustomHeaders:
              -
                HeaderName: Referer
                HeaderValue: !Ref SecretHeaderString
            OriginPath: !Sub "/${ProjectSlug}/production/${GreenVersion}"
        #
        # TODO: cleanup llama should invalidate caches OR max-age should be set
        # on index.html paths.
        #CacheBehaviors:
        #  -
        #    PathPattern: '*/index.html'
        #    TargetOriginId: "blue-green-failover"
        #    ViewerProtocolPolicy: redirect-to-https
        #    # Managed-CachingDisabled
        #    CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
        #  -
        #    PathPattern: '*/'
        #    TargetOriginId: "blue-green-failover"
        #    ViewerProtocolPolicy: redirect-to-https
        #    # Managed-CachingDisabled
        #    CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
        #  -
        #    PathPattern: 'index.html'
        #    TargetOriginId: "blue-green-failover"
        #    ViewerProtocolPolicy: redirect-to-https
        #    # Managed-CachingDisabled
        #    CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
        #  -
        #    PathPattern: '/'
        #    TargetOriginId: "blue-green-failover"
        #    ViewerProtocolPolicy: redirect-to-https
        #    # Managed-CachingDisabled
        #    CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"

  #TODO: Create a hosted zone resource?

  InvalidationPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub "${ProjectSlug}-InvalidationPolicy"
      Roles:
        - Fn::ImportValue:
            "root-S3UpdateWebsiteProductionRoleName"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action:
              - "cloudfront:create-invalidation"
            Resource:
              - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontProduction}"

  DomainNameRoot:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: weboftomorrow.com.
      Type: A
      AliasTarget:
        # Z2FDTNDATAQYW2 is the hosted zone id of cloudfront domain name.
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontProduction.DomainName
  DomainNameWWW:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: www.weboftomorrow.com.
      Type: A
      AliasTarget:
        # Z2FDTNDATAQYW2 is the hosted zone id of cloudfront domain name.
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontProduction.DomainName

Outputs:
  ProductionWebsiteURL:
    Value: !Ref DomainNameRoot
  CloudFrontProduction:
    Value: !Ref CloudFrontProduction
    Export:
      Name: !Sub "${ProjectSlug}-CloudFrontProduction"
